apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-bluegreen-active
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui-bluegreen
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-bluegreen-preview
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui-bluegreen