apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-canary-active
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui-canary
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-canary-preview
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui-canary