apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    app.kubernetes.io/name: guestbook-ui
    app.kubernetes.io/instance: guestbook-ui
    app.kubernetes.io/version: "5"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: principal-unit
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          name: guestbook-ui
          ports:
            - containerPort: 80
